package edu.awt.TeacherEval.Entites;
// Generated Jun 2, 2017 6:08:02 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name = "course", catalog = "teachereval")
public class Course implements java.io.Serializable {

	private int cid;
	private String title;
	private Integer sid;
	private Integer tid;

	public Course() {
	}

	public Course(int cid, String title) {
		this.cid = cid;
		this.title = title;
	}

	public Course(int cid, String title, Integer sid, Integer tid) {
		this.cid = cid;
		this.title = title;
		this.sid = sid;
		this.tid = tid;
	}

	@Id

	@Column(name = "CId", unique = true, nullable = false)
	public int getCid() {
		return this.cid;
	}

	public void setCid(int cid) {
		this.cid = cid;
	}

	@Column(name = "Title", nullable = false, length = 50)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "SId")
	public Integer getSid() {
		return this.sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	@Column(name = "TId")
	public Integer getTid() {
		return this.tid;
	}

	public void setTid(Integer tid) {
		this.tid = tid;
	}

}
