package edu.awt.TeacherEval.Entites;
// Generated Jun 2, 2017 6:08:02 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Proxy;

import java.util.*;

/**
 * Participant generated by hbm2java
 */
@Entity
@Table(name = "participant", catalog = "teachereval")
@Proxy(lazy=true)
public class Participant implements java.io.Serializable {

	@Id
	@Column(name = "PId", unique = true, nullable = false)
	private int PId;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Date", length = 19)
	private Date date;
	
	@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
	@JoinColumn(name="PId")
	private List<Evaluation> evaluation = new ArrayList<Evaluation>();
	

	public List<Evaluation> getEvaluation() {
		return evaluation;
	}

	public void setEvaluation(List<Evaluation> evaluation) {
		this.evaluation = evaluation;
	}

	public Participant() {
	}

	public Participant(int PId) {
		this.PId = PId;
	}

	public Participant(int PId, Date date) {
		this.PId = PId;
		this.date = date;
	}

	
	public int getPId() {
		return this.PId;
	}

	public void setPId(int PId) {
		this.PId = PId;
	}

	
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
