package edu.awt.TeacherEval.Entites;
// Generated Jun 2, 2017 6:08:02 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Questions generated by hbm2java
 */
@Entity
@Table(name = "questions", catalog = "teachereval")
public class Questions implements java.io.Serializable {

	private int qid;
	private String question;
	private String type;

	public Questions() {
	}

	public Questions(int qid, String question) {
		this.qid = qid;
		this.question = question;
	}

	public Questions(int qid, String question, String type) {
		this.qid = qid;
		this.question = question;
		this.type = type;
	}

	@Id
	@Column(name = "QId", unique = true, nullable = false)
	public int getQid() {
		return this.qid;
	}

	public void setQid(int qid) {
		this.qid = qid;
	}

	@Column(name = "Question", nullable = false, length = 200)
	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	@Column(name = "Type", length = 15)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
