package edu.awt.TeacherEval.Entites;
// Generated Jun 2, 2017 6:08:02 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Section generated by hbm2java
 */
@Entity
@Table(name = "section", catalog = "teachereval")
public class Section implements java.io.Serializable {

	private int sid;
	private String section;

	public Section() {
	}

	public Section(int sid) {
		this.sid = sid;
	}

	public Section(int sid, String section) {
		this.sid = sid;
		this.section = section;
	}

	@Id

	@Column(name = "SId", unique = true, nullable = false)
	public int getSid() {
		return this.sid;
	}

	public void setSid(int sid) {
		this.sid = sid;
	}

	@Column(name = "Section", length = 1)
	public String getSection() {
		return this.section;
	}

	public void setSection(String section) {
		this.section = section;
	}

}
