package edu.awt.TeacherEval.Entites;
// Generated Jun 2, 2017 6:08:02 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Teacher generated by hbm2java
 */
@Entity
@Table(name = "teacher", catalog = "teachereval")
public class Teacher implements java.io.Serializable {

	private int tid;
	private String name;
	private String shortName;

	public Teacher() {
	}

	public Teacher(int tid) {
		this.tid = tid;
	}

	public Teacher(int tid, String name, String shortName) {
		this.tid = tid;
		this.name = name;
		this.shortName = shortName;
	}

	@Id

	@Column(name = "Tid", unique = true, nullable = false)
	public int getTid() {
		return this.tid;
	}

	public void setTid(int tid) {
		this.tid = tid;
	}

	@Column(name = "Name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ShortName", length = 5)
	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

}
