package edu.awt.TeacherEval.Entites;
// Generated Jun 2, 2017 6:08:02 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "teachereval")
public class Users implements java.io.Serializable {

	private int regNo;
	private String password;
	private int type;
	private Integer sid;

	public Users() {
	}

	public Users(int regNo, String password, int type) {
		this.regNo = regNo;
		this.password = password;
		this.type = type;
	}

	public Users(int regNo, String password, int type, Integer sid) {
		this.regNo = regNo;
		this.password = password;
		this.type = type;
		this.sid = sid;
	}

	@Id

	@Column(name = "RegNo", unique = true, nullable = false)
	public int getRegNo() {
		return this.regNo;
	}

	public void setRegNo(int regNo) {
		this.regNo = regNo;
	}

	@Column(name = "Password", nullable = false, length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "Type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "SId")
	public Integer getSid() {
		return this.sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

}
